language: go

go:
  - 1.9

services:
  - docker

before_script:
  - chmod +x ./scripts/*.sh

script:
  - ./scripts/build_image.sh
  - ./scripts/deps.sh
  - ./scripts/tests.sh
  - ./scripts/push_image.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)